# Generated by Django 4.1.4 on 2023-01-13 15:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
            ],
            managers=[
                ('empAuth_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
            ],
        ),
    ]
