 # Generated by Django 4.1.4 on 2023-01-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
            ],
        ),
    ]
