# Generated by Django 4.1.4 on 2023-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('contactno', models.CharField(max_length=13)),
                ('services', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='register',
            table='guest_register',
        ),
    ]
